apiVersion: v1
kind: Service
metadata:
  name: animal-shelter-service
  labels:
    app: animal-shelter-service
spec:
  type: NodePort
  selector:
    app: animal-shelter-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
