apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-shelter-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: animal-shelter-service
    spec:
      containers:
        - name: animal-shelter-service
          image: natifani00/animal-shelter-service:7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-user-password
                  name: animal-shelter-db-secret
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: mysql-server
                  name: animal-shelter-db-configmap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: mysql-database-name
                  name: animal-shelter-db-configmap
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: mysql-user-username
                  name: animal-shelter-db-configmap
