apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-shelter-db
  labels:
    app: animal-shelter
spec:
  selector:
    matchLabels:
      app: animal-shelter
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: animal-shelter
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          imagePullPolicy: Always
          name: mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: animal-shelter-db-configmap
                  key: mysql-database-name
            - name: MYSQL_ROOT_PASSWORD
              value: { { DB_ROOT_PASSWORD } }
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: animal-shelter-db-configmap
                  key: mysql-user-username
            - name: MYSQL_PASSWORD
              value: { { DB_USER_PASSWORD } }
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: animal-shelter-db-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: animal-shelter-db-persistent-storage
          persistentVolumeClaim:
            claimName: animal-shelter-db-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'*';
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'*';
    FLUSH PRIVILEGES;
