apiVersion: v1
kind: PersistentVolume
metadata:
  name: animal-shelter-db-pvc
  labels:
    app: animal-shelter
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: animal-shelter-db-pvc
  labels:
    app: animal-shelter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
