apiVersion: v1
kind: Service
metadata:
  name: animal-shelter-db
  labels:
    app: animal-shelter
spec:
  selector:
    app: animal-shelter
    tier: mysql
  ports:
    - port: 3336
      targetPort: 3306
